INSERT INTO pf.receta (id, nombre, nroPaso, tipoFin) VALUES
(1, 'JAMON TIPO 1', 1, 'TEMPERATURA'),
(2, 'JAMON TIPO 2', 2, 'TIEMPO'), 
(3, 'JAMON TIPO 3', 3, 'TEMPERATURA'),
(4, 'JAMON TIPO 4', 4, 'TIEMPO'),
(5, 'JAMON TIPO 5', 5, 'TEMPERATURA'),
(6, 'JAMON TIPO 6', 6, 'TIEMPO');